import { ICard } from './card.types';

export const ALL_CARDS: readonly ICard[] = [
  { id: 1, value: 1, color: 'diamonds' },
  { id: 2, value: 2, color: 'diamonds' },
  { id: 3, value: 3, color: 'diamonds' },
  { id: 4, value: 4, color: 'diamonds' },
  { id: 5, value: 5, color: 'diamonds' },
  { id: 6, value: 6, color: 'diamonds' },
  { id: 7, value: 7, color: 'diamonds' },
  { id: 8, value: 8, color: 'diamonds' },
  { id: 9, value: 9, color: 'diamonds' },
  { id: 10, value: 10, color: 'diamonds' },
  { id: 11, value: 1, color: 'hearts' },
  { id: 12, value: 2, color: 'hearts' },
  { id: 13, value: 3, color: 'hearts' },
  { id: 14, value: 4, color: 'hearts' },
  { id: 15, value: 5, color: 'hearts' },
  { id: 16, value: 6, color: 'hearts' },
  { id: 17, value: 7, color: 'hearts' },
  { id: 18, value: 8, color: 'hearts' },
  { id: 19, value: 9, color: 'hearts' },
  { id: 20, value: 10, color: 'hearts' },
  { id: 21, value: 1, color: 'spades' },
  { id: 22, value: 2, color: 'spades' },
  { id: 23, value: 3, color: 'spades' },
  { id: 24, value: 4, color: 'spades' },
  { id: 25, value: 5, color: 'spades' },
  { id: 26, value: 6, color: 'spades' },
  { id: 27, value: 7, color: 'spades' },
  { id: 28, value: 8, color: 'spades' },
  { id: 29, value: 9, color: 'spades' },
  { id: 30, value: 10, color: 'spades' },
  { id: 31, value: 1, color: 'clubs' },
  { id: 32, value: 2, color: 'clubs' },
  { id: 33, value: 3, color: 'clubs' },
  { id: 34, value: 4, color: 'clubs' },
  { id: 35, value: 5, color: 'clubs' },
  { id: 36, value: 6, color: 'clubs' },
  { id: 37, value: 7, color: 'clubs' },
  { id: 38, value: 8, color: 'clubs' },
  { id: 39, value: 9, color: 'clubs' },
  { id: 40, value: 10, color: 'clubs' },
] as const;
