### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "mario@example.com",
  "name": "Mario Rossi",
  "password": "Password1!"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mario@example.com",
  "password": "Password1!"
}


### Profile (protected)
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjgwY2ViYy03OWFlLTRmMTYtYWY3Mi04MTJjZTA2ZjllNzQiLCJlbWFpbCI6Im1hcmlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTgzNTY2LCJleHAiOjE3NzA5ODcxNjZ9.b8W-B-4kIcjG0xzD51HP_qakji9iMDlx8puBTT_vnUI

