### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "giovanni@example.com",
  "name": "Giovanni Neri",
  "password": "Password1!"
}
### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "giovanni@example.com",
  "password": "Password1!"
}

### Profile (protected)
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4N2Y1YTcyOS0zNmE4LTRiNjQtODBmNS0zNDZmYzQ0YmI1NjIiLCJlbWFpbCI6ImZhYmlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTk2MzM5LCJleHAiOjE3NzA5OTk5Mzl9.cAxfqazJpRL8EYzBzN0gT5QBiViPJSv7kJdBDHSelAo

### Create game
POST http://localhost:3000/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjgwY2ViYy03OWFlLTRmMTYtYWY3Mi04MTJjZTA2ZjllNzQiLCJlbWFpbCI6Im1hcmlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTk2MTk3LCJleHAiOjE3NzA5OTk3OTd9.zeQqerqFNdOx6iJZgHwtpuHU811eZcC15l1WShfJMnM


### Join game (GET)
GET http://localhost:3000/games/a60a2fbd-9a79-4b8c-8f5d-e55fa478488b/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MGViMjA0Ny03YzI3LTQ2MGQtODViYS01NWZkN2Y3OTQ2M2EiLCJlbWFpbCI6Imdpb3Zhbm5pQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTk3MjU3LCJleHAiOjE3NzEwMDA4NTd9.kJW6txjgdccaoFngLvqK4SdLICUaBFk0EYZF3o53qd0
### Delete game
DELETE http://localhost:3000/games/bc0e72ba-c88b-42d6-9455-583c901c416d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjgwY2ViYy03OWFlLTRmMTYtYWY3Mi04MTJjZTA2ZjllNzQiLCJlbWFpbCI6Im1hcmlvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTkxODI0LCJleHAiOjE3NzA5OTU0MjR9.f3PeDw3UHUP0EZdeMpfnT9Zv9bx9BYQSxYTTktsJrLk

### Get all games (JWT required)
GET http://localhost:3000/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MGViMjA0Ny03YzI3LTQ2MGQtODViYS01NWZkN2Y3OTQ2M2EiLCJlbWFpbCI6Imdpb3Zhbm5pQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTk3MjU3LCJleHAiOjE3NzEwMDA4NTd9.kJW6txjgdccaoFngLvqK4SdLICUaBFk0EYZF3o53qd0

### Get game hand (JWT required)
GET http://localhost:3000/games/a60a2fbd-9a79-4b8c-8f5d-e55fa478488b/hand
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MGViMjA0Ny03YzI3LTQ2MGQtODViYS01NWZkN2Y3OTQ2M2EiLCJlbWFpbCI6Imdpb3Zhbm5pQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcwOTk3MjU3LCJleHAiOjE3NzEwMDA4NTd9.kJW6txjgdccaoFngLvqK4SdLICUaBFk0EYZF3o53qd0



Users: 
{
  "email": "mario@example.com",
  "name": "Mario Rossi",
  "password": "Password1!"
}
{
  "email": "carlo@example.com",
  "name": "Carlo Verdi",
  "password": "Password1!"
}
{
  "email": "fabio@example.com",
  "name": "Fabio Bianchi",
  "password": "Password1!"
}
{
  "email": "giovanni@example.com",
  "name": "Giovanni Neri",
  "password": "Password1!"
}

### Login Giovanni
# @name loginGiovanni
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "giovanni@example.com",
  "password": "Password1!"
}

### Profile Giovanni (usa token della risposta sopra)
GET http://localhost:3000/users/profile
Authorization: Bearer {{loginGiovanni.response.body.accessToken}}



